### ISSUE TITLE
Update for tonic `0.11`?

### ISSUE THREAD

**Issue by praveenperera** [arcanyx-pub/tonic-async-interceptor#11]
Hey thanks for the great library. I was wondering if you could update it for tonic 0.11. I tried just bumping the deps, but got some errors, maybe they changed the traits up a bit?

**Comment by jdahlq** [comment]
Hi @praveenperera , I just published 0.11 after #12 was merged, and I've verified it works with tonic 0.11. Sorry for the delay, I'm trying to be a better maintainer, but I have a newborn and a 2-year-old, so it's hard with all the screaming. 😂

**Comment by praveenperera** [comment]
Hey don’t apologize @jdahlq this is helping me for free! I appreciate the update thank you! Congrats on the newborn!
