### ISSUE TITLE
Code example does not work

### ISSUE THREAD

**Issue by xiangsgao** [arcanyx-pub/tonic-async-interceptor#13]
I copied and pasted the same code from the examples. It does not compile. 
I am lost here.

![Screenshot 2024-03-10 221755](https://github.com/arcanyx-pub/tonic-async-interceptor/assets/22754842/98390c4a-9036-45d7-8bbd-c4c6b027e6e6)

**Comment by jdahlq** [comment]
Hi @xiangsgao , thanks for the report. I've just published an updated version, 0.11.0, which works with Tonic version 0.11.0, so if you update your Cargo.toml, it should work now.

**Comment by xiangsgao** [comment]
awesome, works like a charm. thanks
