### ISSUE TITLE
Can this be used for the client interceptor in tonic?

### ISSUE THREAD

**Issue by liufuyang** [arcanyx-pub/tonic-async-interceptor#6]
Coming form here https://github.com/hyperium/tonic/issues/870, I feel perhaps I should ask here is that can this package be used for the client side as well? And how? :)

**Comment by nguquen** [comment]
@liufuyang yes you can, by using tower service like this example https://github.com/hyperium/tonic/blob/eeb3268f71ae5d1107c937392389db63d8f721fb/examples/src/tower/client.rs#L18

```
let channel = Channel::from_static("http://[::1]:50051").connect().await?;

let channel = ServiceBuilder::new()
  .layer(async_interceptor(my_async_interceptor)) // put your async interceptor here
  .service(channel);
let mut client = GreeterClient::new(channel);
```

**Comment by liufuyang** [comment]
Thanks. As it is an old question, I solved my problem without using this package. But I can close this anyway, and it could be useful later on :)

**Comment by jcramb** [comment]
@liufuyang what solution did you come up with?

**Comment by liufuyang** [comment]
Hi @jcramb, it's quite long time ago and I do not exactly remember what issue I was solving, but the implementation I did in the end is just implement a tower Service.

Such as: https://github.com/liufuyang/bigtable_rs/blob/main/bigtable_rs/src/auth_service.rs

And use it like such:
https://github.com/liufuyang/bigtable_rs/blob/5c5107a29feb3bc92356f7bebe0bee54b05906b1/bigtable_rs/src/bigtable.rs#L416

Not sure whether there are better ways to do similar stuff these days. Perhaps you can ask in the tonic discord channel? People usually are very helpful there.
